name: CD

on:
  push:
    branches:
      - 'main'

env:
  # verbosity setting for Terraform logs
  TF_LOG: INFO
  # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # S3 bucket for the Terraform state
  TF_BUCKET_STATE: ${{ secrets.TF_BUCKET_STATE}}
  # Credentials for Confluent Cloud
  TF_VAR_CONFLUENT_CLOUD_API_KEY: ${{ secrets.TF_VAR_CONFLUENT_CLOUD_API_KEY }}
  TF_VAR_CONFLUENT_CLOUD_API_SECRET: ${{ secrets.TF_VAR_CONFLUENT_CLOUD_API_SECRET }}

jobs:
  terraform_data_streaming_platform:
    name: "Terraform Data Streaming Platform"
    #if: github.event.pull_request.merged
    strategy:
      matrix:
        environment: [ staging, prod ]
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        shell: bash
#        working-directory: "${{ matrix.environment }}"
    steps:
      - name: Debug
        run: |
          echo "github.event.pull_request.merged           : ${{ github.event.pull_request.merged }}"
          echo "github.event.pull_request.merged == 'true' : ${{ github.event.pull_request.merged == 'true' }}"
          echo "github.event.pull_request.merged  == true  : ${{ github.event.pull_request.merged == true }}"

      - name: Checkout the repository to the runner
        uses: actions/checkout@v3

#      - name: Get changed folder
#        id: getchange
#        run: |
#          echo "::set-output name=folder::$(git diff --dirstat=files,0 HEAD~1..HEAD | awk '{print $2}')"

#      - name: CD into changed folder
#        run: cd ${{ steps.getchange.outputs.folder }}

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$TF_BUCKET_STATE"
        working-directory: "${{ matrix.environment }}"

      - name: Terraform validate
        id: validate
        run: terraform validate
        working-directory: "${{ matrix.environment }}"

      - name: Terraform workspace
        id: workspace
        run: terraform workspace select ${{ matrix.environment }}
        working-directory: "${{ matrix.environment }}"

      - name: Terraform plan
        id: plan
#        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false -var="confluent_cloud_api_key=$TF_VAR_CONFLUENT_CLOUD_API_KEY -var="confluent_cloud_api_secret=$TF_VAR_CONFLUENT_CLOUD_API_SECRET"
        continue-on-error: true
        working-directory: "${{ matrix.environment }}"

      - uses: actions/github-script@v6
#        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          script: |
            const output = `#### Terraform Format and Style üñå\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ‚öôÔ∏è\`${{ steps.init.outcome }}\`
            #### Terraform Validation ü§ñ\`${{ steps.validate.outcome }}\`
            #### Terraform Plan üìñ\`${{ steps.plan.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            
            </details>
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false


